const recipes = [
 {name:'Market foundation',title:'The foundation.',symbol:'VOO',amount:45000,color:'#c2914b',options:['VOO','VTI','ITOT','SCHB'],note:'Broad US stock exposure. VOO tracks large US companies; total-market funds also include smaller companies.'},
 {name:'Growth',title:'A little ambition.',symbol:'VONG',amount:15000,color:'#9c4940',options:['VONG','VUG','QQQM'],note:'Growth-oriented equities—not a pure technology allocation. Many holdings overlap with broad-market funds.'},
 {name:'Dividends',title:'Something to savor.',symbol:'SCHD',amount:10000,color:'#bb843d',options:['SCHD','VIG','DGRO','DIVO'],note:'Different dividend strategies. DIVO also uses covered calls; distributions and total returns are not guaranteed.'},
 {name:'International',title:'Beyond the familiar.',symbol:'VYMI',amount:10000,color:'#697d55',options:['VYMI','VXUS','VEA','IDVO'],note:'International equities. These funds differ in geography, dividend focus and options use.'},
 {name:'Real assets',title:'From the ground up.',symbol:'GLD',amount:5000,color:'#d3a63e',options:['GLD','SLV','COPX','AA','XOM','EXE'],note:'Gold and silver trusts, mining funds and individual energy/materials companies are different exposures—not interchangeable commodities.'},
 {name:'Crypto',title:'The wild ingredient.',symbol:'BTC',amount:5000,color:'#68477b',options:['BTC','ETH','SOL','IBIT'],note:'Highly volatile. Direct coins and exchange-traded bitcoin exposure differ in structure and risks.'},
 {name:'Coffee / fixed income',title:'Your sleeping pill?',symbol:'SGOV',amount:10000,color:'#dac7a3',options:['SGOV','VBIL','BND','CASH'],note:'The cup is separate from the pie. Treasury-bill funds and BND have very different duration risk. None is the same as insured bank cash.'}
];
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
let selected=0,rebuild=()=>{},focusSlice=()=>{};
function total(){return recipes.reduce((sum,r)=>sum+r.amount,0)}
function renderList(){ $('total').textContent=money(total());$('ingredients').replaceChildren(...recipes.map((r,i)=>{const b=document.createElement('button');b.className='ingredient';b.style.setProperty('--slice',r.color);b.setAttribute('aria-pressed',String(i===selected));const sw=document.createElement('span');sw.className='swatch';const name=document.createElement('span');const sym=document.createElement('span');sym.className='symbol';sym.textContent=r.symbol;const sub=document.createElement('span');sub.className='sub';sub.textContent=r.name;name.append(sym,sub);const portion=document.createElement('span');portion.className='portion';portion.textContent=total()?`${(r.amount/total()*100).toFixed(1)}%`:'0%';b.append(sw,name,portion);b.onclick=()=>select(i);return b}));$('weight').textContent=money(recipes[selected].amount)}
function select(i){selected=i;const r=recipes[i];$('category').textContent=r.name;$('selected-name').textContent=r.title;$('description').textContent=r.note;$('instrument').replaceChildren(...r.options.map(s=>new Option(s,s,false,s===r.symbol)));$('amount').value=r.amount;renderList();focusSlice(i)}
$('instrument').onchange=e=>{recipes[selected].symbol=e.target.value;renderList()};
$('amount').oninput=e=>{if(!e.target.validity.valid||e.target.value==='')return;recipes[selected].amount=Math.max(0,Number(e.target.value)||0);renderList();rebuild()};select(0);
try{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js');init(THREE)}catch(error){$('loading').textContent='The 3D view could not load. Enable WebGL or try another browser. The recipe controls still work.';console.error(error)}
function init(T){
 const stage=$('stage'),scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.1,100);camera.position.set(0,7.8,10.8);camera.lookAt(.25,0,0);
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;stage.append(renderer.domElement);$('loading').hidden=true;
 scene.add(new T.HemisphereLight(0xe3edeb,0x2b2416,2));const light=new T.DirectionalLight(0xffddae,4);light.position.set(-3,8,4);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-6,right:6,top:6,bottom:-6});light.shadow.bias=-.0002;light.shadow.normalBias=.025;scene.add(light);const rim=new T.DirectionalLight(0xbcd2e2,2.5);rim.position.set(3,4,-5);scene.add(rim);
 const mat=(color,roughness=.7)=>new T.MeshStandardMaterial({color,roughness});const crust=mat('#b67935'),edge=mat('#d29d56'),ceramic=mat('#b9c4b4',.24),coffeeMat=mat('#241308',.16);
 // Fine baked-surface relief from a deterministic noise texture, not a flat illustration.
 const size=128,data=new Uint8Array(size*size*4);let seed=21;for(let i=0;i<data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const n=80+seed%175;data[i]=data[i+1]=data[i+2]=n;data[i+3]=255}const grain=new T.DataTexture(data,size,size);grain.needsUpdate=true;grain.wrapS=grain.wrapT=T.RepeatWrapping;grain.repeat.set(6,6);for(const m of [crust,edge]){m.bumpMap=grain;m.bumpScale=.045}
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),mat('#252b24',.9));floor.rotation.x=-Math.PI/2;floor.position.y=-.11;floor.receiveShadow=true;scene.add(floor);scene.fog=new T.Fog('#1a201b',17,34);
 function mesh(geo,material,parent,x=0,y=0,z=0){const m=new T.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 const root=new T.Group();root.position.x=-.6;scene.add(root);
 mesh(new T.CylinderGeometry(2.73,2.62,.12,100),ceramic,root,0,0,0);const plateRim=mesh(new T.TorusGeometry(2.64,.105,12,120),ceramic,root,0,.10,0);plateRim.rotation.x=Math.PI/2;
 const pie=new T.Group();root.add(pie);let groups=[],expanded=false,spin=false,targetRotation=-.4;pie.rotation.y=targetRotation;
 function wedge(radius,a,b,depth,material,parent,y){const shape=new T.Shape();shape.moveTo(0,0);shape.lineTo(radius*Math.cos(a),radius*Math.sin(a));shape.absarc(0,0,radius,a,b,false);shape.lineTo(0,0);const geom=new T.ExtrudeGeometry(shape,{depth,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.018,bevelThickness:.018,curveSegments:40});geom.rotateX(-Math.PI/2);return mesh(geom,material,parent,0,y,0)}
 function clearPie(){pie.traverse(o=>{if(o.isMesh){o.geometry.dispose();if(o.userData.ownMaterial)o.material.dispose()}});pie.clear();groups=[]}
 rebuild=()=>{clearPie();const sum=recipes.slice(0,6).reduce((s,r)=>s+r.amount,0);let start=0;recipes.slice(0,6).forEach((r,i)=>{if(!r.amount||!sum)return;const end=start+r.amount/sum*Math.PI*2, gap=Math.min(.014,(end-start)*.1),a=start+gap,b=end-gap,g=new T.Group();g.userData={index:i,mid:(a+b)/2};pie.add(g);groups.push(g);wedge(2.27,a,b,.10,crust,g,.13);const filling=mat(r.color,.48);filling.bumpMap=grain;filling.bumpScale=.055;const fill=wedge(2.19,a,b,.40,filling,g,.25);fill.userData.ownMaterial=true;
 // A fluted pastry edge follows each wedge so the lifted slice is a complete object.
 const n=Math.max(2,Math.ceil((b-a)*18));for(let j=0;j<=n;j++){const angle=a+(b-a)*j/n;const fl=mesh(new T.SphereGeometry(.115,8,6),j%3===0?crust:edge,g,2.20*Math.cos(angle),.64,-2.20*Math.sin(angle));fl.scale.set(1,.8,1)}
 // Clipped lattice strips follow the actual slice boundary.
 for(let x=-1.9;x<2;x+=.38){let run=[];const flush=()=>{if(run.length>1){const first=run[0],last=run[run.length-1];mesh(new T.BoxGeometry(.10,.055,last-first+.07),edge,g,x,.69,(first+last)/2)}run=[]};for(let z=-2.05;z<=2.05;z+=.065){let ang=Math.atan2(-z,x);if(ang<0)ang+=Math.PI*2;if(x*x+z*z<4.1&&ang>a&&ang<b)run.push(z);else flush()}flush()}
 start=end});};rebuild();
 const cup=new T.Group();cup.position.set(2.8,.04,-.9);cup.scale.setScalar(.86);scene.add(cup);mesh(new T.CylinderGeometry(.94,.87,.07,64),ceramic,cup);const points=[[.43,.10],[.48,.12],[.58,.32],[.64,.85],[.62,.91],[.57,.90],[.54,.34],[.42,.19]].map(p=>new T.Vector2(...p));mesh(new T.LatheGeometry(points,64),ceramic,cup);mesh(new T.CylinderGeometry(.565,.565,.018,64),coffeeMat,cup,0,.78,0);const handle=mesh(new T.TorusGeometry(.30,.075,12,40),ceramic,cup,.68,.51,0);handle.scale.x=.82;
 const steamMaterial=new T.MeshBasicMaterial({color:'#d8d3bd',transparent:true,opacity:.13,depthWrite:false});const steam=[];for(let i=0;i<3;i++){const pts=[];for(let j=0;j<16;j++)pts.push(new T.Vector3(Math.sin(j*.5+i)*.06+i*.14-.14,.94+j*.045,0));const line=mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),24,.014,5,false),steamMaterial,cup);steam.push(line)}
 const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;focusSlice=i=>{if(i<6){const g=groups.find(g=>g.userData.index===i);if(g){const desired=-g.userData.mid-Math.PI/2;targetRotation=pie.rotation.y+Math.atan2(Math.sin(desired-pie.rotation.y),Math.cos(desired-pie.rotation.y))}}};focusSlice(0);
 $('spread').onclick=()=>{expanded=!expanded;$('spread').setAttribute('aria-pressed',String(expanded));$('spread').textContent=expanded?'Bring slices together':'Separate slices'};$('rotate').onclick=()=>{spin=!spin;$('rotate').setAttribute('aria-pressed',String(spin));$('rotate').textContent=spin?'Stop rotation':'Rotate the plate'};
 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null,moved=false;
 renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};moved=false});renderer.domElement.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-down.x;if(Math.abs(dx)>3)moved=true;if(moved){targetRotation+=dx*.008;down.x=e.clientX}});renderer.domElement.addEventListener('pointercancel',()=>down=null);renderer.domElement.addEventListener('pointerleave',()=>down=null);renderer.domElement.addEventListener('pointerup',e=>{if(!down)return;down=null;if(moved)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([...groups,cup],true);if(hits.length){let o=hits[0].object;while(o.parent&&o.parent!==pie&&o!==cup)o=o.parent;select(o===cup?6:o.userData.index??selected)}});
 new ResizeObserver(()=>{const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=camera.aspect<1?14:10.8;camera.updateProjectionMatrix()}).observe(stage);
 let last=0;function animate(time){requestAnimationFrame(animate);if(document.hidden)return;const dt=Math.min((time-last)/1000,.05);last=time;const ease=reduce?1:1-Math.exp(-dt*7);if(spin)targetRotation+=dt*.22;pie.rotation.y+=(targetRotation-pie.rotation.y)*ease;for(const g of groups){const active=g.userData.index===selected,dist=expanded?.42:active?.30:0;g.position.x+=(Math.cos(g.userData.mid)*dist-g.position.x)*ease;g.position.z+=(-Math.sin(g.userData.mid)*dist-g.position.z)*ease;g.position.y+=((active?.62:0)-g.position.y)*ease;g.rotation.z+=((active?-.055:0)-g.rotation.z)*ease}cup.position.y+=((selected===6?.24:.04)-cup.position.y)*ease;steam.forEach((s,i)=>{if(!reduce)s.rotation.y=Math.sin(time*.0007+i)*.5});renderer.render(scene,camera)}requestAnimationFrame(animate);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').hidden=false;$('loading').textContent='3D paused by your browser. Reload to restore it; your recipe controls are still available.'});
}
